name: py310
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - libffi=3.4.4
  - openssl=1.1.1t
  - pip=23.0.1
  - python=3.10.11
  - setuptools=67.8.0
  - sqlite=3.41.2
  - tk=8.6.12
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - accelerate==0.20.3
    - aiofiles==23.1.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==5.0.1
    - anyio==3.7.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.2.3
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==23.1.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.2
    - bleach==6.0.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - charset-normalizer==3.1.0
    - click==8.1.3
    - colorama==0.4.6
    - comm==0.1.3
    - contourpy==1.1.0
    - cycler==0.11.0
    - debugpy==1.6.7
    - decorator==5.1.1
    - defusedxml==0.7.1
    - diffusers==0.17.1
    - exceptiongroup==1.1.1
    - executing==1.2.0
    - fastapi==0.98.0
    - fastjsonschema==2.17.1
    - ffmpy==0.3.0
    - filelock==3.12.2
    - fonttools==4.40.0
    - fqdn==1.5.1
    - frozenlist==1.3.3
    - fsspec==2023.6.0
    - gradio==3.35.2
    - gradio-client==0.2.7
    - h11==0.14.0
    - httpcore==0.17.2
    - httpx==0.24.1
    - huggingface-hub==0.15.1
    - idna==3.4
    - importlib-metadata==6.7.0
    - ipykernel==6.23.2
    - ipython==8.14.0
    - ipython-genutils==0.2.0
    - ipywidgets==8.0.6
    - isoduration==20.11.0
    - jedi==0.18.2
    - jinja2==3.1.2
    - jsonpointer==2.4
    - jsonschema==4.17.3
    - jupyter==1.0.0
    - jupyter-client==8.2.0
    - jupyter-console==6.6.3
    - jupyter-core==5.3.1
    - jupyter-events==0.6.3
    - jupyter-server==2.6.0
    - jupyter-server-terminals==0.4.4
    - jupyterlab-pygments==0.2.2
    - jupyterlab-widgets==3.0.7
    - kiwisolver==1.4.4
    - linkify-it-py==2.0.2
    - markdown-it-py==2.2.0
    - markupsafe==2.1.3
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - mistune==3.0.1
    - mpmath==1.3.0
    - multidict==6.0.4
    - mypy-extensions==1.0.0
    - nbclassic==1.0.0
    - nbclient==0.8.0
    - nbconvert==7.6.0
    - nbformat==5.9.0
    - nest-asyncio==1.5.6
    - networkx==3.1
    - notebook==6.5.4
    - notebook-shim==0.2.3
    - numpy==1.25.0
    - orjson==3.9.1
    - overrides==7.3.1
    - packaging==23.1
    - pandas==2.0.2
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pickleshare==0.7.5
    - pillow==9.5.0
    - platformdirs==3.8.0
    - prometheus-client==0.17.0
    - prompt-toolkit==3.0.38
    - psutil==5.9.5
    - pure-eval==0.2.2
    - pycparser==2.21
    - pydantic==1.10.9
    - pydub==0.25.1
    - pygments==2.15.1
    - pyparsing==3.1.0
    - pypng==0.20220715.0
    - pyre-extensions==0.0.29
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-json-logger==2.0.7
    - python-multipart==0.0.6
    - pytz==2023.3
    - pywin32==306
    - pywinpty==2.0.10
    - pyyaml==6.0
    - pyzbar==0.1.9
    - pyzmq==25.1.0
    - qrcode==7.4.2
    - qtconsole==5.4.3
    - qtpy==2.3.1
    - regex==2023.6.3
    - requests==2.31.0
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - safetensors==0.3.1
    - semantic-version==2.10.0
    - send2trash==1.8.2
    - six==1.16.0
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - stack-data==0.6.2
    - starlette==0.27.0
    - sympy==1.12
    - terminado==0.17.1
    - tinycss2==1.2.1
    - tokenizers==0.13.3
    - toolz==0.12.0
    - torch==2.0.1+cu117
    - torchaudio==2.0.2+cu117
    - torchvision==0.15.2+cu117
    - tornado==6.3.2
    - tqdm==4.65.0
    - traitlets==5.9.0
    - transformers==4.30.2
    - typing-extensions==4.6.3
    - typing-inspect==0.9.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - uri-template==1.3.0
    - urllib3==2.0.3
    - uvicorn==0.22.0
    - wcwidth==0.2.6
    - webcolors==1.13
    - webencodings==0.5.1
    - websocket-client==1.6.0
    - websockets==11.0.3
    - widgetsnbextension==4.0.7
    - xformers==0.0.20
    - yarl==1.9.2
    - zipp==3.15.0
